### ISSUE TITLE
wikidata

### ISSUE THREAD

**Issue by shainaraza** [malteos/pytorch-bert-document-classification#2]
considering the large size of wikidata, can you suggest some condensed verison for wikidata?
thanks in advance

**Comment by malteos** [comment]
To my knowledge partial or condensed versions do not exist. So you need to download the full set of embeddings and then extract the ones you need (see https://github.com/malteos/pytorch-bert-document-classification/blob/master/wikidata_for_authors.py#L30 )

If you just need to ones used in our paper, you can download them here:

https://github.com/malteos/pytorch-bert-document-classification/blob/master/extras/author2embedding.pickle
